/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-14 10:51:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.musicstore.model.Feedback;

public final class feedback_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.musicstore.model.Feedback");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Music Store Feedback</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Reset CSS */\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            background-image: url('background.jpg'); \r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-attachment: fixed;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            min-height: 100vh; \r\n");
      out.write("            position: relative; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .person-section {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: -300px; \r\n");
      out.write("            top: 80%;\r\n");
      out.write("            transform: translateY(-50%);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .person-section img {\r\n");
      out.write("            width: 200px; \r\n");
      out.write("            height: auto; \r\n");
      out.write("            margin-bottom: 10px; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .person-section p {\r\n");
      out.write("            font-size: 16px; \r\n");
      out.write("            color: #541550; \r\n");
      out.write("            font-style: italic;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        .navbar {\r\n");
      out.write("            background-color: rgba(0, 51, 102, 0.8); \r\n");
      out.write("            color: #FFF; /\r\n");
      out.write("            padding: 10px 0; \r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-radius: 0 0 10px 10px; \r\n");
      out.write("            position: relative; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        .navbar a {\r\n");
      out.write("            color: #FFF; \r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            margin: 0 20px; \r\n");
      out.write("            font-size: 18px; \r\n");
      out.write("            transition: color 0.3s; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .navbar a:hover {\r\n");
      out.write("            color: #FFC300; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .logo {\r\n");
      out.write("            width: 80px; \r\n");
      out.write("            height: 40px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: 20px;\r\n");
      out.write("            transform: translateY(-50%); \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 800px;\r\n");
      out.write("            margin: 50px auto;\r\n");
      out.write("            position: relative; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .submit-feedback-box {\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            background-color: rgba(255, 255, 255, 0.9); \r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("        .existing-feedback-box {\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            background-color: rgba(255, 255, 255, 0.9); \r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("        h1 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("        form {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        input[type=\"text\"],\r\n");
      out.write("        input[type=\"email\"],\r\n");
      out.write("        textarea {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            background-color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("            border: 1px solid rgba(0, 0, 0, 0.2);\r\n");
      out.write("            transition: border-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"text\"]:focus,\r\n");
      out.write("        input[type=\"email\"]:focus,\r\n");
      out.write("        textarea:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border-color: #007bff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        button[type=\"submit\"] {\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 14px 20px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button[type=\"submit\"]:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th, td {\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border-bottom: 1px solid #ddd;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th {\r\n");
      out.write("            background-color: #f2f2f2;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .btn-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .btn-container button {\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-container button:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .footer {\r\n");
      out.write("            background-color: rgba(0, 51, 102, 0.8); \r\n");
      out.write("            color: #FFF; \r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 10px 0; \r\n");
      out.write("            border-radius: 0 0 10px 10px; \r\n");
      out.write("            position: absolute; \r\n");
      out.write("            bottom: -5; \r\n");
      out.write("            width: 100%; \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write(".btn-container button[type=\"button\"] {\r\n");
      out.write("    background-color: #007bff; \r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    padding: 10px 20px; /\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("    margin-right: 10px; \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".btn-container form button[type=\"submit\"] {\r\n");
      out.write("    background-color: #dc3545; /* Red color */\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    padding: 10px 20px; /\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("    margin-rights: 10px; \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    .btn-container button[type=\"button\"]:hover {\r\n");
      out.write("        background-color: #0056b3; \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-container form button[type=\"submit\"]:hover {\r\n");
      out.write("        background-color: #c82333; /\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("    <script>\r\n");
      out.write("        // JavaScript function to show popup message\r\n");
      out.write("        function showPopup(message) {\r\n");
      out.write("            alert(message);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // JavaScript function to show the edit form\r\n");
      out.write("        function showEditForm(id, name, email, comment) {\r\n");
      out.write("            document.getElementById('edit-feedback-id').value = id;\r\n");
      out.write("            document.getElementById('edit-name').value = name;\r\n");
      out.write("            document.getElementById('edit-email').value = email;\r\n");
      out.write("            document.getElementById('edit-comment').value = comment;\r\n");
      out.write("            document.getElementById('edit-feedback-box').style.display = 'block';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // JavaScript function to hide the edit form\r\n");
      out.write("        function hideEditForm() {\r\n");
      out.write("            document.getElementById('edit-feedback-box').style.display = 'none';\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"navbar\">\r\n");
      out.write("        <img src=\"logo.png\" alt=\"Logo\" class=\"logo\">\r\n");
      out.write("        <a href=\"#\">Home</a>\r\n");
      out.write("        <a href=\"#\">About</a>\r\n");
      out.write("        <a href=\"#\">Contact</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!-- Person Image and Text Section -->\r\n");
      out.write("        <div class=\"person-section\">\r\n");
      out.write("            <img src=\"person.png\" alt=\"Person Image\">\r\n");
      out.write("            <p><b>\"This is amazing!\"<br>Lahiru Chamara<br>~CEO WinTech~</b></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Submit New Feedback Section -->\r\n");
      out.write("        <div class=\"submit-feedback-box\">\r\n");
      out.write("            <h1 class=\"mt-5 mb-4\">Submit New Feedback</h1>\r\n");
      out.write("            <form action=\"submitFeedback?action=create\" method=\"post\" onsubmit=\"showPopup('Feedback has submitted successfully!')\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"name\">Name:</label>\r\n");
      out.write("                    <input type=\"text\" id=\"name\" name=\"name\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"email\">Email:</label>\r\n");
      out.write("                    <input type=\"email\" id=\"email\" name=\"email\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"comment\">Comment:</label>\r\n");
      out.write("                    <textarea id=\"comment\" name=\"comment\" rows=\"4\" required></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\">Submit</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Edit Feedback Box -->\r\n");
      out.write("        <div id=\"edit-feedback-box\" class=\"submit-feedback-box\" style=\"display: none;\">\r\n");
      out.write("            <h1>Edit Feedback</h1>\r\n");
      out.write("            <form action=\"submitFeedback?action=update\" method=\"post\" onsubmit=\"showPopup('Feedback has updated successfully!')\">\r\n");
      out.write("                <input type=\"hidden\" id=\"edit-feedback-id\" name=\"id\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"edit-name\">Name:</label>\r\n");
      out.write("                    <input type=\"text\" id=\"edit-name\" name=\"name\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"edit-email\">Email:</label>\r\n");
      out.write("                    <input type=\"email\" id=\"edit-email\" name=\"email\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"edit-comment\">Comment:</label>\r\n");
      out.write("                    <textarea id=\"edit-comment\" name=\"comment\" rows=\"4\" required></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\">Update</button>\r\n");
      out.write("                <button type=\"button\" onclick=\"hideEditForm()\">Cancel</button>\r\n");
      out.write("                \r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Existing Feedback Section -->\r\n");
      out.write("        <div class=\"existing-feedback-box\">\r\n");
      out.write("            <h1 class=\"mt-5 mb-4\">Existing Feedback</h1>\r\n");
      out.write("            <table>\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>ID</th>\r\n");
      out.write("                        <th>Name</th>\r\n");
      out.write("                        <th>Email</th>\r\n");
      out.write("                        <th>Comment</th>\r\n");
      out.write("                        <th>Action</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");

                        // Get feedbackList from request attribute
                        List<Feedback> feedbackList = (List<Feedback>) request.getAttribute("feedbackList");
                        
                        // Check if feedbackList is not null and not empty
                        if (feedbackList != null && !feedbackList.isEmpty()) {
                            // Iterate through the feedbackList
                            for (Feedback feedback : feedbackList) {
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print( feedback.getId() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( feedback.getName() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( feedback.getEmail() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( feedback.getComment() );
      out.write("</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div class=\"btn-container\">\r\n");
      out.write("                                <button type=\"button\" onclick=\"showEditForm('");
      out.print( feedback.getId() );
      out.write("', '");
      out.print( feedback.getName() );
      out.write("', '");
      out.print( feedback.getEmail() );
      out.write("', '");
      out.print( feedback.getComment() );
      out.write("')\">Edit</button>\r\n");
      out.write("                                <form action=\"submitFeedback\" method=\"post\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"action\" value=\"delete\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"id\" value=\"");
      out.print( feedback.getId() );
      out.write("\">\r\n");
      out.write("                                    <button type=\"submit\">Delete</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                            } 
                        } else { 
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"5\">No feedback available</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                        } 
                    
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        &copy; 2024 \"තනුව\" Music Store. All rights reserved.\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
